/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': 'var(--color-primary)',
        'primary-container': 'var(--color-primary-container)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'on-primary': '#ffffff',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'secondary': '#525f73',
        'secondary-container': '#d6e3fb',
        'secondary-fixed': '#d6e3fb',
        'secondary-fixed-dim': '#bac7de',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#0f1c2d',
        'on-secondary-fixed-variant': '#3b485a',
        'on-secondary-container': '#586579',
        'tertiary': '#003955',
        'tertiary-container': '#005177',
        'tertiary-fixed': '#c9e6ff',
        'tertiary-fixed-dim': '#8bceff',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#001e2f',
        'on-tertiary-fixed-variant': '#004b6f',
        'on-tertiary-container': '#71c5ff',
        'surface': '#f8f9fa',
        'surface-bright': '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-tint': 'var(--color-surface-tint)',
        'surface-variant': '#e1e3e4',
        'surface-container': '#edeeef',
        'surface-container-low': '#f3f4f5',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#191c1d',
        'on-surface-variant': '#424751',
        'background': '#f8f9fa',
        'on-background': '#191c1d',
        'outline': '#737783',
        'outline-variant': '#c2c6d3',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': 'var(--color-inverse-primary)',
        'accent-50': 'var(--color-accent-50)',
        'accent-100': 'var(--color-accent-100)',
        'accent-600': 'var(--color-accent-600)',
        'accent-700': 'var(--color-accent-700)',
        'accent-900': 'var(--color-accent-900)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
