BEGIN;

-- Clear existing data
DELETE FROM project_activity_logs;
DELETE FROM project_members;
UPDATE project_records SET assigned_to = NULL;
DELETE FROM project_records;
DELETE FROM project_columns;
DELETE FROM projects;
DELETE FROM approvals;
DELETE FROM activity_logs;
DELETE FROM notifications;
DELETE FROM tickets;
DELETE FROM refresh_tokens;
DELETE FROM users;

-- Seed 106 users
-- Password: Pcs@2024

INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Daniel T Pesireron', 'daniel.pesireron@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'admin', true, NULL, NULL, NULL, NULL, NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Yonanda Syafriade', 'yonanda.syafriade@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'approver', true, (SELECT id FROM divisions WHERE name = 'BIZ' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Business' AND dv.name = 'BIZ' LIMIT 1), NULL, 'manager', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Andreas Rivaldo', 'andreas.rivaldo@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'BIZ' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Business' AND dv.name = 'BIZ' LIMIT 1), NULL, 'manager', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Bondan Ramadhan', 'bondan.ramadhan@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'BIZ' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Business' AND dv.name = 'BIZ' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Account' AND d.name = 'Business' AND dv.name = 'BIZ' LIMIT 1), 'leader', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Iwan Yustito Hia', 'iwan.hia@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'BIZ' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Business' AND dv.name = 'BIZ' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Business Support' AND d.name = 'Business' AND dv.name = 'BIZ' LIMIT 1), 'leader', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Indra Susilo', 'indra.susilo@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'BIZ' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Business' AND dv.name = 'BIZ' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Sales Executive' AND d.name = 'Business' AND dv.name = 'BIZ' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Ana Riswati', 'ana.riswati@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'approver', true, (SELECT id FROM divisions WHERE name = 'DOS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Finance, Accounting & Tax' AND dv.name = 'DOS' LIMIT 1), NULL, 'manager', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Faradina Marlizar', 'faradina.marlizar@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'DOS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Finance, Accounting & Tax' AND dv.name = 'DOS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Accountant' AND d.name = 'Finance, Accounting & Tax' AND dv.name = 'DOS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Eka Sylvia Pangastuti', 'eka.pangastuti@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'DOS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Finance, Accounting & Tax' AND dv.name = 'DOS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Finance' AND d.name = 'Finance, Accounting & Tax' AND dv.name = 'DOS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Nindyasari Rukmana', 'nindyasari.rukmana@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'approver', true, (SELECT id FROM divisions WHERE name = 'DOS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'GSL' AND dv.name = 'DOS' LIMIT 1), NULL, 'manager', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Susmaili Bungsu', 'susmaili.bungsu@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'DOS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'GSL' AND dv.name = 'DOS' LIMIT 1), NULL, 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Jungjunan Fauzan', 'jungjunan.fauzan@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'DOS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'GSL' AND dv.name = 'DOS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Data Logistic' AND d.name = 'GSL' AND dv.name = 'DOS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Abit Budin', 'abit.budin@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'DOS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'GSL' AND dv.name = 'DOS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Data Repair' AND d.name = 'GSL' AND dv.name = 'DOS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Suganda', 'suganda@email.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'DOS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'GSL' AND dv.name = 'DOS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Driver' AND d.name = 'GSL' AND dv.name = 'DOS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Saut Harapan Lumbantoruan', 'saut.lumbantoruan@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'DOS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'GSL' AND dv.name = 'DOS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Legal' AND d.name = 'GSL' AND dv.name = 'DOS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Sarifudin', 'udin@email.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'DOS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'GSL' AND dv.name = 'DOS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Office Boy' AND d.name = 'GSL' AND dv.name = 'DOS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Dita Novita Sari', 'dita.novitasari@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'DOS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'GSL' AND dv.name = 'DOS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Procurement' AND d.name = 'GSL' AND dv.name = 'DOS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Atied Danutriyadi', 'atied@email.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'DOS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'GSL' AND dv.name = 'DOS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Security' AND d.name = 'GSL' AND dv.name = 'DOS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Dimas Aryo Kunto Wibisono', 'dimas.wibisono@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'approver', true, (SELECT id FROM divisions WHERE name = 'DOS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Human Resources' AND dv.name = 'DOS' LIMIT 1), NULL, 'manager', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Muhammad Aldian Sevana', 'aldian.sevana@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'DOS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Human Resources' AND dv.name = 'DOS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'HR General' AND d.name = 'Human Resources' AND dv.name = 'DOS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Fahreza Novarian', 'fahreza.novarian@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'DOS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Human Resources' AND dv.name = 'DOS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'HRBP Ops' AND d.name = 'Human Resources' AND dv.name = 'DOS' LIMIT 1), 'leader', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Erik Zakaria Santosa', 'erik.santosa@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'approver', true, (SELECT id FROM divisions WHERE name = 'Event Organizer' LIMIT 1), NULL, NULL, 'manager', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Saskia Ichnati Chandri', 'saskia.chandri@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'Event Organizer' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'Event Organizer' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Digital Marketing' AND d.name = 'Marketing' AND dv.name = 'Event Organizer' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Reza Fachriansyah', 'reza.fachriansyah@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'Event Organizer' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'Event Organizer' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Documentation' AND d.name = 'Marketing' AND dv.name = 'Event Organizer' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Julida Santika LG', 'julida.santika@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'Event Organizer' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'Event Organizer' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Public Relations' AND d.name = 'Marketing' AND dv.name = 'Event Organizer' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Rachmad Kurniawan', 'rachmad.kurniawan@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'Event Organizer' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Operation' AND dv.name = 'Event Organizer' LIMIT 1), NULL, 'manager', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Annia Yosepha', 'annia.yosepha@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'Event Organizer' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Operation' AND dv.name = 'Event Organizer' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Finance & Admin' AND d.name = 'Operation' AND dv.name = 'Event Organizer' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Ahmad Farhan', 'ahmad.farhan@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'Event Organizer' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Operation' AND dv.name = 'Event Organizer' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Tenant Coordinator' AND d.name = 'Operation' AND dv.name = 'Event Organizer' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Erwin Fransiscus', 'erwin.fransiscus@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'approver', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), NULL, NULL, 'manager', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Septyan Azany', 'septyan.azany@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'C&G' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Cybersecurity' AND d.name = 'C&G' AND dv.name = 'IT' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Muhammad Ja''far Shodiq', 'muhammad.shodiq@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'C&G' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'GRC' AND d.name = 'C&G' AND dv.name = 'IT' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Ryan Kenedy', 'ryan.kenedy@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'ITOps' AND dv.name = 'IT' LIMIT 1), NULL, 'manager', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Yudho Prakoso', 'yudho.prakoso@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'ITOps' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Data Engineer' AND d.name = 'ITOps' AND dv.name = 'IT' LIMIT 1), 'leader', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Erwin Aji Nugroho', 'erwin.nugroho@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'ITOps' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Database Optimizer' AND d.name = 'ITOps' AND dv.name = 'IT' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Achya Syahputra', 'achya.syahputra@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'ITOps' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'DevOps' AND d.name = 'ITOps' AND dv.name = 'IT' LIMIT 1), 'leader', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Nazar Syah Dumyati', 'nazar.dumyati@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'ITOps' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'PPQA' AND d.name = 'ITOps' AND dv.name = 'IT' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Aditya Warman', 'aditya.warman@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'ITOps' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'PsOps' AND d.name = 'ITOps' AND dv.name = 'IT' LIMIT 1), 'leader', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Mega Yunita', 'mega.yunita@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'ITOps' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Service Desk' AND d.name = 'ITOps' AND dv.name = 'IT' LIMIT 1), 'leader', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Vanesha Asyariza', 'vanesha.asyariza@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'PSD' AND dv.name = 'IT' LIMIT 1), NULL, 'manager', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Yeni Herawati', 'yeni.herawati@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'PSD' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'BQA' AND d.name = 'PSD' AND dv.name = 'IT' LIMIT 1), 'leader', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Jihan Nabilah', 'jihan.nabilah@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'PSD' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Business Analyst' AND d.name = 'PSD' AND dv.name = 'IT' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Tata Bayu Amarta', 'tata.amarta@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'PSD' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Project Manager' AND d.name = 'PSD' AND dv.name = 'IT' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Nila Humairah', 'nila.humairah@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'PSD' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Technical Writer' AND d.name = 'PSD' AND dv.name = 'IT' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Bagus Wijayana', 'bagus.wijayana@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'PSD' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'UI/UX' AND d.name = 'PSD' AND dv.name = 'IT' LIMIT 1), 'leader', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'M Arif Yudhistira', 'm.yudhistira@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'R&D' AND dv.name = 'IT' LIMIT 1), NULL, 'manager', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Hanif Murtadha Tsaniputra', 'hanif.tsaniputra@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'R&D' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'BackEnd' AND d.name = 'R&D' AND dv.name = 'IT' LIMIT 1), 'leader', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Muhamad Febri Algani', 'muhammad.algani@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'R&D' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'FrontEnd' AND d.name = 'R&D' AND dv.name = 'IT' LIMIT 1), 'leader', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Nauval Adiyasa', 'nauval.adiyasa@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'R&D' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Mobile X' AND d.name = 'R&D' AND dv.name = 'IT' LIMIT 1), 'leader', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Kelvin Prayitno', 'kelvin.prayitno@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'IT' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'R&D' AND dv.name = 'IT' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Mobile Y' AND d.name = 'R&D' AND dv.name = 'IT' LIMIT 1), 'leader', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Dicky Maturama', 'dicky.maturama@kjsindonesia.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'approver', true, (SELECT id FROM divisions WHERE name = 'KJS' LIMIT 1), NULL, NULL, 'manager', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Ayu Nuraini Putri', 'aputri@kjsindonesia.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'KJS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Account Executive' AND dv.name = 'KJS' LIMIT 1), NULL, 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Heni Widiastuti', 'heni.widiastuti@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'KJS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Finance' AND dv.name = 'KJS' LIMIT 1), NULL, 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Anggi Afriadi', 'anggi.afriadi@kjsindonesia.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'KJS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Operation' AND dv.name = 'KJS' LIMIT 1), NULL, 'manager', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Ainun Lina Huda Nur Syahadhah', 'ainun.syahadhah@kjsindonesia.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'KJS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Operation' AND dv.name = 'KJS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Admin' AND d.name = 'Operation' AND dv.name = 'KJS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'M Rizqi Inaya', 'mrizqi.inaya@kjsindonesia.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'KJS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Operation' AND dv.name = 'KJS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'NPO' AND d.name = 'Operation' AND dv.name = 'KJS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Aris Karangan', 'aris.karangan@kjsindonesia.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'KJS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Operation' AND dv.name = 'KJS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Project Manager' AND d.name = 'Operation' AND dv.name = 'KJS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Jujun Junaedi', 'jujun.junaedi@kjsindonesia.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'KJS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Operation' AND dv.name = 'KJS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'RF' AND d.name = 'Operation' AND dv.name = 'KJS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Bagas Al Hafizh', 'bagas.hafizh@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'approver', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'HO Excellent Performance Operation' AND dv.name = 'OPS' LIMIT 1), NULL, 'manager', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Rizky Arifandy', 'rizky.arifandy@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'HO Excellent Performance Operation' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Implementation & Dismantle' AND d.name = 'HO Excellent Performance Operation' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Muhamad Ilham Nugraha', 'muhamad.nugraha@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'HO Excellent Performance Operation' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Liason Officer' AND d.name = 'HO Excellent Performance Operation' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Renata Adesti', 'renata.adesti@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'HO Excellent Performance Operation' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Preventive Maintenance' AND d.name = 'HO Excellent Performance Operation' AND dv.name = 'OPS' LIMIT 1), 'leader', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Pramelya Kharisma', 'pramelya.kharisma@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'HO Excellent Performance Operation' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Reconcilliation & Assurance' AND d.name = 'HO Excellent Performance Operation' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Omar Saladdin', 'omar.saladdin@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'approver', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'HO Strategic Business Operation' AND dv.name = 'OPS' LIMIT 1), NULL, 'manager', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Kurnia Hendradi', 'kurnia.hendradi@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'HO Strategic Business Operation' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'POSe Mobile' AND d.name = 'HO Strategic Business Operation' AND dv.name = 'OPS' LIMIT 1), 'leader', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Muhammad Raihan Alviano', 'muhammad.alviano@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), NULL, 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Imal Rahman', 'imal.rahman@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), NULL, 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Mochammad Arif Naufalyanto', 'm.naufalyanto@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), NULL, 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Rizal Renaldy', 'rizal.renaldi@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), NULL, 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Jiroris Ahmar', 'jiroris.ahmar@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), NULL, 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Ayu Apriliani', 'ayu.apriliani@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Admin RO' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Danar Prabowo Wihandoko', 'danar.wihandoko@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Admin RO Jakarta 1' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Asep Saepurohman', 'asep.saepurohman@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Admin RO Jakarta 3' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Rizka Herza Putri', 'rizka.putri@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Admin RO Riau' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Lia Apriani', 'lia.apriani@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Admin RO Sumbagsel' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Chindyta Putri Irma', 'chindyta.irma@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Admin RO Sumbagut' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Ade Ravi Putra Arya', 'ade.arya@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Gst Kadek Raka Septio Kaesar', 'gst.kaesar@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader EPO' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Aswar Aswar', 'aswar@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader EPO & SBO' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Rizky Dewantoro', 'rizky.dewantoro@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader EPO & SBO Banjarmasin' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'M. Ardeansyah Eka Putra Arbain', 'ardeansyah.arbain@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader EPO & SBO Kaltim' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Toya Muthia Septinabilla', 'toya.septinabila@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader EPO & SBO Riau' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Hardadi Fajar Nurhendro', 'hardadi.nurhendro@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader EPO & SBO Sumbagsel' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Syahrul Ramadhan', 'syahrul.ramadhan@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader EPO & SBO Sumbar' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Dioga Giffara PK', 'dioga.giffara@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader EPO Depok - Bogor' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Muhammad Fazri', 'muhammad.fazri@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader EPO Jakbar' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Dimas Prasetyo', 'dimas.prasetyo@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader EPO Sumbagut' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Syahrul Fauzi', 'syahrul.fauzi@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader EPO bekasi - Jaktim' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Muhammad Rizqie Maldini', 'muhammad.maldini@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader SBO' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Fajar Gunawan', 'fajar.gunawan@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader SBO Bekasi' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Muhamad Rizky Ramadhan', 'rizky.ramadhan@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader SBO Jakbar' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Yustitia Putri Irma', 'yustitia.irma@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader SBO Sumbagut' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Angga Afriansyah', 'angga.afriansyah@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Leader Sumatera' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Dayanti Fariska', 'dayanti@email.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'PIC Asset' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Iwan Yasyir', 'pandanabtq@gmail.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'SOA' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Mohamad Firdaus', 'firstdaus1@gmail.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'SOA Jakarta 1' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Nanda Firdaus', 'nandafirdaus257@gmail.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'SOA Jakarta 2' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Venny Cahyawati', 'vennywati16@gmail.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'SOA Jakarta 3' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Ronald Ferdinand Marcos Sitorus', 'ronaldsitorus271@gmail.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'SOA Sumbagut' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Syuref Mahasra', 'syurefmahasra90@gmail.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'OPS' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'SOA Sumbar' AND d.name = 'Regional Office' AND dv.name = 'OPS' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Muhamad Andi Rafdi', 'muhamad.rafdi@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'approver', true, (SELECT id FROM divisions WHERE name = 'S&M' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M' LIMIT 1), NULL, 'manager', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Sindi Nurkhairunisa', 'sindi.nurkhairunisa@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'S&M' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Event Partnership' AND d.name = 'Marketing' AND dv.name = 'S&M' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Eriansyah Raihan Fachrurrozi', 'eriansyah.fachrurrozi@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'S&M' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Graphic Designer' AND d.name = 'Marketing' AND dv.name = 'S&M' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Chaedar Ambadar', 'chaedar.ambadar@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'S&M' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Offline Marketing' AND d.name = 'Marketing' AND dv.name = 'S&M' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Dimas Gilang Radistya', 'dimas.radistya@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'S&M' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Online Sales' AND d.name = 'Marketing' AND dv.name = 'S&M' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Septie Miranda Ayuri', 'septie.ayuri@pcsindonesia.co.id', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'S&M' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Telemarketing' AND d.name = 'Marketing' AND dv.name = 'S&M' LIMIT 1), 'staff', NOW(), NOW());
INSERT INTO users (id, full_name, email, password, role, is_active, division_id, department_id, team_id, position, created_at, updated_at)
VALUES (gen_random_uuid(), 'Amanta Berliantino', 'beno@email.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user', true, (SELECT id FROM divisions WHERE name = 'S&M' LIMIT 1), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Sales' AND dv.name = 'S&M' LIMIT 1), (SELECT t.id FROM teams t JOIN departments d ON t.department_id = d.id JOIN divisions dv ON d.division_id = dv.id WHERE t.name = 'Quality Control' AND d.name = 'Sales' AND dv.name = 'S&M' LIMIT 1), 'staff', NOW(), NOW());

-- Set reports_to
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'yonanda.syafriade@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'erwin.fransiscus@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'dicky.maturama@kjsindonesia.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'muhamad.rafdi@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'erik.santosa@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'yonanda.syafriade@pcsindonesia.co.id') WHERE email = 'andreas.rivaldo@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'ana.riswati@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'nindyasari.rukmana@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'dimas.wibisono@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'erwin.fransiscus@pcsindonesia.co.id') WHERE email = 'ryan.kenedy@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'erwin.fransiscus@pcsindonesia.co.id') WHERE email = 'vanesha.asyariza@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'erwin.fransiscus@pcsindonesia.co.id') WHERE email = 'm.yudhistira@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'dicky.maturama@kjsindonesia.com') WHERE email = 'anggi.afriadi@kjsindonesia.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'bagas.hafizh@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'omar.saladdin@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'erik.santosa@pcsindonesia.co.id') WHERE email = 'rachmad.kurniawan@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'dicky.maturama@kjsindonesia.com') WHERE email = 'heni.widiastuti@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'imal.rahman@pcsindonesia.co.id') WHERE email = 'vennywati16@gmail.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'erwin.fransiscus@pcsindonesia.co.id') WHERE email = 'septyan.azany@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'dicky.maturama@kjsindonesia.com') WHERE email = 'aputri@kjsindonesia.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'muhamad.rafdi@pcsindonesia.co.id') WHERE email = 'beno@email.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'erik.santosa@pcsindonesia.co.id') WHERE email = 'julida.santika@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'andreas.rivaldo@pcsindonesia.co.id') WHERE email = 'bondan.ramadhan@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'andreas.rivaldo@pcsindonesia.co.id') WHERE email = 'iwan.hia@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'dimas.wibisono@pcsindonesia.co.id') WHERE email = 'fahreza.novarian@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'vanesha.asyariza@pcsindonesia.co.id') WHERE email = 'yeni.herawati@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'm.yudhistira@pcsindonesia.co.id') WHERE email = 'kelvin.prayitno@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'm.yudhistira@pcsindonesia.co.id') WHERE email = 'hanif.tsaniputra@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'm.yudhistira@pcsindonesia.co.id') WHERE email = 'muhammad.algani@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'm.yudhistira@pcsindonesia.co.id') WHERE email = 'nauval.adiyasa@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'vanesha.asyariza@pcsindonesia.co.id') WHERE email = 'bagus.wijayana@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'ryan.kenedy@pcsindonesia.co.id') WHERE email = 'achya.syahputra@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'ryan.kenedy@pcsindonesia.co.id') WHERE email = 'mega.yunita@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'ryan.kenedy@pcsindonesia.co.id') WHERE email = 'yudho.prakoso@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'ryan.kenedy@pcsindonesia.co.id') WHERE email = 'aditya.warman@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'bagas.hafizh@pcsindonesia.co.id') WHERE email = 'renata.adesti@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'omar.saladdin@pcsindonesia.co.id') WHERE email = 'kurnia.hendradi@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'andreas.rivaldo@pcsindonesia.co.id') WHERE email = 'indra.susilo@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'ana.riswati@pcsindonesia.co.id') WHERE email = 'faradina.marlizar@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'susmaili.bungsu@pcsindonesia.co.id') WHERE email = 'suganda@email.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'ana.riswati@pcsindonesia.co.id') WHERE email = 'eka.pangastuti@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'dimas.wibisono@pcsindonesia.co.id') WHERE email = 'aldian.sevana@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'susmaili.bungsu@pcsindonesia.co.id') WHERE email = 'udin@email.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'susmaili.bungsu@pcsindonesia.co.id') WHERE email = 'atied@email.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'vanesha.asyariza@pcsindonesia.co.id') WHERE email = 'jihan.nabilah@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'erwin.fransiscus@pcsindonesia.co.id') WHERE email = 'muhammad.shodiq@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'ryan.kenedy@pcsindonesia.co.id') WHERE email = 'nazar.dumyati@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'vanesha.asyariza@pcsindonesia.co.id') WHERE email = 'tata.amarta@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'vanesha.asyariza@pcsindonesia.co.id') WHERE email = 'nila.humairah@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'muhamad.rafdi@pcsindonesia.co.id') WHERE email = 'sindi.nurkhairunisa@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'muhamad.rafdi@pcsindonesia.co.id') WHERE email = 'eriansyah.fachrurrozi@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'muhamad.rafdi@pcsindonesia.co.id') WHERE email = 'chaedar.ambadar@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'muhamad.rafdi@pcsindonesia.co.id') WHERE email = 'dimas.radistya@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'muhamad.rafdi@pcsindonesia.co.id') WHERE email = 'septie.ayuri@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'susmaili.bungsu@pcsindonesia.co.id') WHERE email = 'jungjunan.fauzan@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'susmaili.bungsu@pcsindonesia.co.id') WHERE email = 'abit.budin@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'susmaili.bungsu@pcsindonesia.co.id') WHERE email = 'dita.novitasari@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'ryan.kenedy@pcsindonesia.co.id') WHERE email = 'erwin.nugroho@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'bagas.hafizh@pcsindonesia.co.id') WHERE email = 'rizky.arifandy@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'bagas.hafizh@pcsindonesia.co.id') WHERE email = 'muhamad.nugraha@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'bagas.hafizh@pcsindonesia.co.id') WHERE email = 'pramelya.kharisma@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'imal.rahman@pcsindonesia.co.id') WHERE email = 'dayanti@email.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'anggi.afriadi@kjsindonesia.com') WHERE email = 'ainun.syahadhah@kjsindonesia.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'anggi.afriadi@kjsindonesia.com') WHERE email = 'jujun.junaedi@kjsindonesia.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'muhammad.alviano@pcsindonesia.co.id') WHERE email = 'pandanabtq@gmail.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'susmaili.bungsu@pcsindonesia.co.id') WHERE email = 'saut.lumbantoruan@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'anggi.afriadi@kjsindonesia.com') WHERE email = 'mrizqi.inaya@kjsindonesia.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'rizal.renaldi@pcsindonesia.co.id') WHERE email = 'ayu.apriliani@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'rizal.renaldi@pcsindonesia.co.id') WHERE email = 'gst.kaesar@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'rizal.renaldi@pcsindonesia.co.id') WHERE email = 'muhammad.maldini@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'rizal.renaldi@pcsindonesia.co.id') WHERE email = 'ade.arya@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'imal.rahman@pcsindonesia.co.id') WHERE email = 'nandafirdaus257@gmail.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'imal.rahman@pcsindonesia.co.id') WHERE email = 'danar.wihandoko@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'imal.rahman@pcsindonesia.co.id') WHERE email = 'asep.saepurohman@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'imal.rahman@pcsindonesia.co.id') WHERE email = 'syahrul.fauzi@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'imal.rahman@pcsindonesia.co.id') WHERE email = 'dioga.giffara@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'imal.rahman@pcsindonesia.co.id') WHERE email = 'muhammad.fazri@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'imal.rahman@pcsindonesia.co.id') WHERE email = 'fajar.gunawan@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'imal.rahman@pcsindonesia.co.id') WHERE email = 'rizky.ramadhan@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'imal.rahman@pcsindonesia.co.id') WHERE email = 'firstdaus1@gmail.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'jiroris.ahmar@pcsindonesia.co.id') WHERE email = 'ronaldsitorus271@gmail.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'jiroris.ahmar@pcsindonesia.co.id') WHERE email = 'syurefmahasra90@gmail.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'rizky.dewantoro@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'ardeansyah.arbain@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'm.naufalyanto@pcsindonesia.co.id') WHERE email = 'aswar@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'jiroris.ahmar@pcsindonesia.co.id') WHERE email = 'rizka.putri@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'jiroris.ahmar@pcsindonesia.co.id') WHERE email = 'lia.apriani@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'jiroris.ahmar@pcsindonesia.co.id') WHERE email = 'chindyta.irma@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'jiroris.ahmar@pcsindonesia.co.id') WHERE email = 'toya.septinabila@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'jiroris.ahmar@pcsindonesia.co.id') WHERE email = 'hardadi.nurhendro@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'jiroris.ahmar@pcsindonesia.co.id') WHERE email = 'syahrul.ramadhan@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'jiroris.ahmar@pcsindonesia.co.id') WHERE email = 'dimas.prasetyo@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'jiroris.ahmar@pcsindonesia.co.id') WHERE email = 'angga.afriansyah@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'jiroris.ahmar@pcsindonesia.co.id') WHERE email = 'yustitia.irma@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'anggi.afriadi@kjsindonesia.com') WHERE email = 'aris.karangan@kjsindonesia.com';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'rachmad.kurniawan@pcsindonesia.co.id') WHERE email = 'annia.yosepha@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'rachmad.kurniawan@pcsindonesia.co.id') WHERE email = 'ahmad.farhan@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'erik.santosa@pcsindonesia.co.id') WHERE email = 'reza.fachriansyah@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'erik.santosa@pcsindonesia.co.id') WHERE email = 'saskia.chandri@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'nindyasari.rukmana@pcsindonesia.co.id') WHERE email = 'susmaili.bungsu@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'muhammad.alviano@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'imal.rahman@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'm.naufalyanto@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'rizal.renaldi@pcsindonesia.co.id';
UPDATE users SET reports_to = (SELECT id FROM users WHERE email = 'daniel.pesireron@pcsindonesia.co.id') WHERE email = 'jiroris.ahmar@pcsindonesia.co.id';

COMMIT;
