BEGIN;

-- Seed org structure from Excel: Division -> Department -> Team

-- Divisions (top level)
INSERT INTO divisions (id, name, code) VALUES (gen_random_uuid(), 'BIZ', 'BIZ');
INSERT INTO divisions (id, name, code) VALUES (gen_random_uuid(), 'DOS', 'DOS');
INSERT INTO divisions (id, name, code) VALUES (gen_random_uuid(), 'Event Organizer', 'EO');
INSERT INTO divisions (id, name, code) VALUES (gen_random_uuid(), 'IT', 'IT');
INSERT INTO divisions (id, name, code) VALUES (gen_random_uuid(), 'KJS', 'KJS');
INSERT INTO divisions (id, name, code) VALUES (gen_random_uuid(), 'OPS', 'OPS');
INSERT INTO divisions (id, name, code) VALUES (gen_random_uuid(), 'Operation', 'OPR');
INSERT INTO divisions (id, name, code) VALUES (gen_random_uuid(), 'S&M', 'SNM');

-- Departments (child of Division)
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'BIZ'), 'Business', 'BUS');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'DOS'), 'Finance, Accounting & Tax', 'FAT');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'DOS'), 'GSL', 'GSL');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'DOS'), 'HRGA', 'HRG');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'DOS'), 'Human Resources', 'HR');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'Event Organizer'), 'Marketing', 'MAR');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'Event Organizer'), 'Operation', 'OPE');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'IT'), 'C&G', 'C&G');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'IT'), 'ITOps', 'ITO');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'IT'), 'PSD', 'PSD');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'IT'), 'R&D', 'R&D');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'KJS'), 'Account Executive', 'AE');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'KJS'), 'Finance', 'FIN');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'KJS'), 'Operation', 'OPE');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'KJS'), 'Product', 'PRO');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'OPS'), 'HO Excellent Performance Operation', 'HEPO');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'OPS'), 'HO Strategic Business Operation', 'HSBO');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'OPS'), 'Regional Office', 'RO');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'S&M'), 'BCA Retail', 'BR');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'S&M'), 'MNC', 'MNC');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'S&M'), 'Marketing', 'MAR');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'S&M'), 'POSe BRI Chain ', 'PBC');
INSERT INTO departments (id, division_id, name, code) VALUES (gen_random_uuid(), (SELECT id FROM divisions WHERE name = 'S&M'), 'Sales', 'SAL');

-- Teams (child of Department)
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Business' AND dv.name = 'BIZ'), 'Account');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Business' AND dv.name = 'BIZ'), 'Business Development');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Business' AND dv.name = 'BIZ'), 'Business Support');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Business' AND dv.name = 'BIZ'), 'Sales Executive');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Finance, Accounting & Tax' AND dv.name = 'DOS'), 'Accountant');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Finance, Accounting & Tax' AND dv.name = 'DOS'), 'Finance');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Finance, Accounting & Tax' AND dv.name = 'DOS'), 'Tax');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'GSL' AND dv.name = 'DOS'), 'Data Logistic');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'GSL' AND dv.name = 'DOS'), 'Data Repair');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'GSL' AND dv.name = 'DOS'), 'Driver');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'GSL' AND dv.name = 'DOS'), 'Legal');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'GSL' AND dv.name = 'DOS'), 'Office Boy');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'GSL' AND dv.name = 'DOS'), 'Procurement');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'GSL' AND dv.name = 'DOS'), 'Security');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Human Resources' AND dv.name = 'DOS'), 'HR General');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Human Resources' AND dv.name = 'DOS'), 'HR Service');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Human Resources' AND dv.name = 'DOS'), 'HRBP Ops');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'Event Organizer'), 'Digital Marketing');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'Event Organizer'), 'Documentation');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'Event Organizer'), 'Public Relations');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Operation' AND dv.name = 'Event Organizer'), 'Finance & Admin');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Operation' AND dv.name = 'Event Organizer'), 'Tenant Coordinator');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'C&G' AND dv.name = 'IT'), 'Cybersecurity');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'C&G' AND dv.name = 'IT'), 'GRC');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'ITOps' AND dv.name = 'IT'), 'Data Engineer');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'ITOps' AND dv.name = 'IT'), 'Database Optimizer');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'ITOps' AND dv.name = 'IT'), 'DevOps');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'ITOps' AND dv.name = 'IT'), 'PPQA');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'ITOps' AND dv.name = 'IT'), 'PsOps');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'ITOps' AND dv.name = 'IT'), 'Service Desk');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'PSD' AND dv.name = 'IT'), 'BQA');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'PSD' AND dv.name = 'IT'), 'Business Analyst');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'PSD' AND dv.name = 'IT'), 'Project Manager');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'PSD' AND dv.name = 'IT'), 'Technical Writer');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'PSD' AND dv.name = 'IT'), 'UI/UX');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'R&D' AND dv.name = 'IT'), 'BackEnd');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'R&D' AND dv.name = 'IT'), 'FrontEnd');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'R&D' AND dv.name = 'IT'), 'Mobile X');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'R&D' AND dv.name = 'IT'), 'Mobile Y');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Operation' AND dv.name = 'KJS'), 'Admin');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Operation' AND dv.name = 'KJS'), 'NPO');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Operation' AND dv.name = 'KJS'), 'Project Manager');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Operation' AND dv.name = 'KJS'), 'RF');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'HO Excellent Performance Operation' AND dv.name = 'OPS'), 'Dismantle');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'HO Excellent Performance Operation' AND dv.name = 'OPS'), 'Helpdesk');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'HO Excellent Performance Operation' AND dv.name = 'OPS'), 'Implementation & Dismantle');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'HO Excellent Performance Operation' AND dv.name = 'OPS'), 'Liason Officer');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'HO Excellent Performance Operation' AND dv.name = 'OPS'), 'Preventive Maintenance');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'HO Excellent Performance Operation' AND dv.name = 'OPS'), 'Reconcilliation & Assurance');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'HO Strategic Business Operation' AND dv.name = 'OPS'), 'KerjaYuk!');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'HO Strategic Business Operation' AND dv.name = 'OPS'), 'POSe Mobile');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Admin RO');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Admin RO ');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Admin RO Jakarta 1');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Admin RO Jakarta 2');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Admin RO Jakarta 3');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Admin RO Riau');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Admin RO Sumbagsel');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Admin RO Sumbagut');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader EPO');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader EPO & SBO');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader EPO & SBO Banjarmasin');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader EPO & SBO Batam');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader EPO & SBO Kaltim');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader EPO & SBO Riau');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader EPO & SBO Sumbagsel');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader EPO & SBO Sumbar');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader EPO Depok - Bogor');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader EPO Jakbar');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader EPO Jakpus - Jakut');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader EPO Jaksel');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader EPO Sumbagut');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader EPO Tangerang');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader EPO bekasi - Jaktim');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader Jakarta');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader SBO');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader SBO Bekasi');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader SBO Jakbar');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader SBO Jaksel');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader SBO Sumbagut');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader SBO Tangerang');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'Leader Sumatera');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'PIC Asset');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'SOA');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'SOA Jakarta 1');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'SOA Jakarta 2');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'SOA Jakarta 3');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'SOA Sumbagut');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Regional Office' AND dv.name = 'OPS'), 'SOA Sumbar');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'BCA Retail' AND dv.name = 'S&M'), 'Admin & Reconciliation');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'BCA Retail' AND dv.name = 'S&M'), 'Leader');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'BCA Retail' AND dv.name = 'S&M'), 'Leader 2');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M'), 'Digital Marketing');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M'), 'Event Coordinator');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M'), 'Event Partnership');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M'), 'Graphic Designer');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M'), 'Marketing Specialist');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M'), 'Offline Marketing');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M'), 'Online Sales');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M'), 'SEO');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M'), 'Social Media');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M'), 'Telemarketing');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Marketing' AND dv.name = 'S&M'), 'Video Editor');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'POSe BRI Chain ' AND dv.name = 'S&M'), 'Sales Executive');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Sales' AND dv.name = 'S&M'), 'Admin & Payroll');
INSERT INTO teams (id, department_id, name) VALUES (gen_random_uuid(), (SELECT d.id FROM departments d JOIN divisions dv ON d.division_id = dv.id WHERE d.name = 'Sales' AND dv.name = 'S&M'), 'Quality Control');

COMMIT;
