# PRODUCTION SECRETS
# PENTING: Ganti semua value dengan base64-encoded secret production
# Encode: echo -n "value-asli" | base64
apiVersion: v1
kind: Secret
metadata:
  name: itsm-secrets
  namespace: ticketing
type: Opaque
data:
  # echo -n "itsm" | base64
  DB_USER: aXRzbQ==
  # echo -n "GANTI_PASSWORD_DB_PRODUCTION" | base64
  DB_PASSWORD: R0FOVElfUEFTU1dPUkRfREJfUFJPRFVDVElPTg==
  # echo -n "itsm" | base64
  DB_NAME: aXRzbQ==
  # echo -n "GANTI_JWT_SECRET_PRODUCTION" | base64
  JWT_SECRET: R0FOVElfSldUX1NFQ1JFVF9QUk9EVUNUSU9O
  # echo -n "GANTI_JWT_REFRESH_SECRET_PRODUCTION" | base64
  JWT_REFRESH_SECRET: R0FOVElfSldUX1JFRlJFU0hfU0VDUkVUX1BST0RVQ1RJT04=
  # echo -n "GANTI_WEBHOOK_SECRET" | base64
  WEBHOOK_SECRET: R0FOVElfV0VCSE9PS19TRUNSRVQ=
  # echo -n "fQJ2KcEdkq943n@" | base64
  APP_EMAIL_SMTP_PASS: ZlFKMktjRWRrcTk0M25A
  # echo -n "LbIqo1zptvgOPk2LTv8GdWAq8x0DSHrh" | base64
  KEYCLOAK_CLIENT_SECRET: TGJJcW8xenB0dmdPUGsyTFR2OEdkV0FxOHgwRFNIcmg=
